# Authors: Arthur Cadore M. Barcella
#          Deivid Fortinato Frederico
#          Matheus Pires Salazar
#          Rhenzo Hideki S. Kajikawa
# PJI2 - Projeto Integrador 2 IFSC-SJ

version: '3'
services:
  #----------------------------------------------------------------------------
  # Serviço do mosquitto 
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      # Mapeia a portas 1883 do host para porta 1883 do container
      - "1883:1883"
      # - "9001:9001"
    volumes:
      # Mapeia os arquivos de configuração
      - ./src/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
  #----------------------------------------------------------------------------
  # Serviço para um interpretador Python
  pythoninterpreter:
    container_name: pythoninterpreter
    build:
      # Constroi a imagem a partir desse contexto local 
      context: ./src/python
    restart: always
    depends_on:
      - database
  #----------------------------------------------------------------------------
  # Serviço para um Database 
  database:
    container_name: database
    build:
      # Constroi a imagem a partir desse contexto local 
      context: ./src/database/
    ports:
      # Mapeia a porta do host 3306 para porta 3306 do container
      - "3306:3306"
    environment:
      # Define a senha do root do MySQL
      MYSQL_ROOT_PASSWORD: cadore#dbmqtt
  #----------------------------------------------------------------------------
  # Serviço para uma aplicação WEB
  mqttbackend:
    container_name: mqttbackend
    build:
      # Constroi a imagem a partir desse contexto local 
      context: ./src/backend/
    ports:
      # Mapeia a porta do host 3000 para porta 3300 do container
      - "3000:3000"
    volumes:
      # Mapeia os arquivos de configuração
      - ./src/backend/MqttBroker:/project
    restart: always
    depends_on:
      - database
