version: '3'
services:

    mosquitto:
      image: eclipse-mosquitto:2.0.18
      container_name: mosquitto
      ports:
        - "1883:1883"
        # - "9001:9001"
      volumes:
        - ./src/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      restart: always
    
    pythoninterpreter:
      container_name: pythoninterpreter
      build:
        context: ./src/python
      restart: always
      depends_on:
        - database

    database:
      container_name: database
      build:
        context: ./src/database/ 
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: cadore#dbmqtt

    mqttfront:
      container_name: mqttfront
      build:
        context: ./src/frontend/
      ports:
        - "80:3000"
      restart: always
